# Generated by Django 5.2.4 on 2025-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clickstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('event_context', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('origin', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
